// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbz_LygfRQ0ybSXS6lQxxjs8XmvAZRDbmG72EsH0SFrunmFG_Qy56BGS5eXrCgcZ3h7M/exec";
